{{- include "openuem.validateDatabase" . }}
{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "openuem.cnpgClusterName" . }}
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    {{- with .Values.cnpg.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.cnpg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  instances: {{ .Values.cnpg.instances }}
  imageName: {{ .Values.cnpg.imageName }}
  primaryUpdateStrategy: {{ .Values.cnpg.primaryUpdateStrategy }}
  enableSuperuserAccess: {{ .Values.cnpg.enableSuperuserAccess }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database }}
      owner: {{ .Values.cnpg.owner }}
      {{- with .Values.cnpg.existingSecret }}
      secret:
        name: {{ . }}
      {{- end }}
  storage:
    size: {{ .Values.cnpg.storage.size }}
    {{- with .Values.cnpg.storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  {{- if .Values.cnpg.walStorage.enabled }}
  walStorage:
    size: {{ .Values.cnpg.walStorage.size }}
    {{- with .Values.cnpg.walStorage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.cnpg.parameters }}
  postgresql:
    parameters:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- if .Values.cnpg.monitoring.enablePodMonitor }}
  monitoring:
    enablePodMonitor: true
  {{- end }}
  {{- with .Values.cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cnpg.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cnpg.backup }}
  backup:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cnpg.extraSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
