apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "openuem.fullname" . }}-cert-init
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
    app.kubernetes.io/component: cert-init
spec:
  backoffLimit: {{ .Values.certInit.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.certInit.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "openuem.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cert-init
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openuem.serviceAccountName" . }}
      restartPolicy: OnFailure
      initContainers:
        - name: cleanup-empty-dirs
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Cleaning up empty directories that should be files..."
              # Remove empty directories recursively (created by subPath mounts)
              find /certificates -type d -empty -delete 2>/dev/null || true
              echo "Cleanup complete"
          volumeMounts:
            - name: openuem-certs
              mountPath: /certificates
              subPath: certificates
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-db
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              while ! nc -z {{ include "openuem.postgresqlServiceName" . }} {{ .Values.postgresql.port }}; do
                echo "Waiting for PostgreSQL..."
                sleep 3
              done
        {{- end }}
      containers:
        - name: cert-init
          image: "{{ include "openuem.imageRegistry" . }}{{ .Values.certInit.image.repository }}:{{ .Values.certInit.image.tag }}"
          imagePullPolicy: {{ .Values.certInit.image.pullPolicy }}
          command: ["/bin/configure.sh"]
          env:
            - name: ORGNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: ORGNAME
            - name: ORGPROVINCE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: ORGPROVINCE
            - name: ORGLOCALITY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: ORGLOCALITY
            - name: ORGADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: ORGADDRESS
            - name: COUNTRY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: COUNTRY
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: DOMAIN
            - name: OCSP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: OCSP
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "openuem.databaseSecretName" . }}
                  key: DATABASE_URL
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "openuem.fullname" . }}-config
                  key: SERVER_NAME
            - name: NATS_SERVER
              value: {{ include "openuem.natsHostname" . | quote }}
            - name: NATS_PORT
              value: {{ .Values.natsConfig.port | quote }}
            {{- if .Values.certInit.reverseProxyServer }}
            - name: REVERSE_PROXY_SERVER
              value: {{ .Values.certInit.reverseProxyServer | quote }}
            {{- end }}
          {{- with .Values.certInit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: openuem-certs
              mountPath: /certificates
              subPath: certificates
            - name: openuem-certs
              mountPath: /etc/nats
              subPath: nats
      volumes:
        - name: openuem-certs
          persistentVolumeClaim:
            claimName: {{ include "openuem.certsPvcName" . }}
