apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openuem.certsPvcName" . }}
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.certInit.persistence.accessModes | nindent 4 }}
  {{- if .Values.certInit.persistence.storageClass }}
  storageClassName: {{ .Values.certInit.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.certInit.persistence.size }}
