{{- $needsDBUrl := not .Values.externalDatabase.existingSecret }}
{{- $needsJWT := not .Values.console.existingSecret }}
{{- $needsPG := and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
{{- if or $needsDBUrl $needsJWT $needsPG }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openuem.fullname" . }}-secret
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needsDBUrl }}
  DATABASE_URL: {{ include "openuem.databaseUrl" . | quote }}
  {{- end }}
  {{- if $needsJWT }}
  JWT_KEY: {{ .Values.console.jwtKey | quote }}
  {{- end }}
  {{- if $needsPG }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  {{- end }}
{{- end }}
