{{- if .Values.traefik.ingressRoute.enabled }}
{{- if not .Values.traefik.ingressRoute.console.host }}
{{- fail "traefik.ingressRoute.console.host is required when traefik.ingressRoute.enabled=true" }}
{{- end }}
{{- if not .Values.traefik.ingressRoute.auth.host }}
{{- fail "traefik.ingressRoute.auth.host is required when traefik.ingressRoute.enabled=true" }}
{{- end }}
apiVersion: {{ .Values.traefik.ingressRoute.apiVersion }}
kind: IngressRoute
metadata:
  name: {{ include "openuem.fullname" . }}-console
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- with .Values.traefik.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.traefik.ingressRoute.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.console.host }}`)
      kind: Rule
      services:
        - name: {{ include "openuem.fullname" . }}-console
          port: {{ .Values.console.service.port }}
  {{- if or .Values.traefik.ingressRoute.console.tls.certResolver .Values.traefik.ingressRoute.console.tls.secretName }}
  tls:
    {{- with .Values.traefik.ingressRoute.console.tls.certResolver }}
    certResolver: {{ . }}
    {{- end }}
    {{- with .Values.traefik.ingressRoute.console.tls.secretName }}
    secretName: {{ . }}
    {{- end }}
  {{- end }}
---
apiVersion: {{ .Values.traefik.ingressRoute.apiVersion }}
kind: IngressRoute
metadata:
  name: {{ include "openuem.fullname" . }}-auth
  labels:
    {{- include "openuem.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- with .Values.traefik.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.traefik.ingressRoute.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.auth.host }}`)
      kind: Rule
      services:
        - name: {{ include "openuem.fullname" . }}-console
          port: {{ .Values.console.service.authPort }}
  {{- if or .Values.traefik.ingressRoute.auth.tls.certResolver .Values.traefik.ingressRoute.auth.tls.secretName }}
  tls:
    {{- with .Values.traefik.ingressRoute.auth.tls.certResolver }}
    certResolver: {{ . }}
    {{- end }}
    {{- with .Values.traefik.ingressRoute.auth.tls.secretName }}
    secretName: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
